spring.application.name=proyecto

# Server Port
server.port=8080

# MySQL datasource



spring.datasource.url=mysql://root:thonWkmNlQDIHmYDfWlslrZqRsyBVqHP@reseau.proxy.rlwy.net:13563/railway
spring.datasource.username=root
spring.datasource.password=thonWkmNlQDIHmYDfWlslrZqRsyBVqHP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# JPA / Hibernate


# Las semillas de datos se cargan desde DataInitializer.java
# OAuth2 - Google Login
spring.security.oauth2.client.registration.google.client-id=1028495367416-91rev7da2jrpu9cvo6pbh4vaq14qrrmt.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}



